package com.aistudy.server.source.asset.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;

import java.time.LocalDateTime;

/**
 * BUSINESS-004 — production SourceAsset persistence model.
 *
 * <p>Backs the {@code source_asset} table (V008 migration). One row =
 * one RAW file object of a Source (data-model.md §5.2): the original
 * ZIP ({@code ORIGINAL_PACKAGE}) or an original PDF/image/markdown/
 * text file ({@code ORIGINAL_FILE}). The RAW bytes live in
 * {@link com.aistudy.server.storage.StorageService}; this row is
 * metadata + the cross-platform {@link #storageKey} only (ADR-033,
 * NFR-DATA-003 — never an absolute path).
 *
 * <h3>Ownership model</h3>
 *
 * <p>Deliberately NO {@code ownerSubject} column: ownership derives
 * from the parent chain {@code source_asset -> source ->
 * learning_space}. Every read is an owner-scoped SQL JOIN
 * (id + spaceId + sourceId + owner in one query) and upload validates
 * the parent source via {@code SourceService.getMine()} first
 * (BUSINESS-004 D1/D2 anti-IDOR).
 *
 * <h3>Server-controlled fields</h3>
 *
 * <p>{@code assetRole} is derived from the file extension by the
 * service (.zip → ORIGINAL_PACKAGE, allowlist → ORIGINAL_FILE);
 * {@code storageKey} is generated by StorageService; {@code sha256}
 * and {@code sizeBytes} come from the stored stream. Clients never
 * submit any of them (the upload endpoint accepts only the
 * multipart file part).
 *
 * <h3>MyBatis-Plus mapping</h3>
 *
 * <p>{@code @TableName("source_asset")} + {@code @TableId(type =
 * IdType.AUTO)} follow the project convention; camelCase fields map
 * to snake_case columns via {@code map-underscore-to-camel-case}.
 * No business rules live here — they are in
 * {@link com.aistudy.server.source.asset.service.SourceAssetService}.
 */
@TableName("source_asset")
public class SourceAsset {

    @TableId(type = IdType.AUTO)
    private Long id;

    private Long spaceId;

    private Long sourceId;

    private String assetRole;

    private String originalName;

    private String originalRelativePath;

    private String storageKey;

    private String mimeType;

    private Long sizeBytes;

    private String sha256;

    private LocalDateTime createdAt;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getSpaceId() {
        return spaceId;
    }

    public void setSpaceId(Long spaceId) {
        this.spaceId = spaceId;
    }

    public Long getSourceId() {
        return sourceId;
    }

    public void setSourceId(Long sourceId) {
        this.sourceId = sourceId;
    }

    public String getAssetRole() {
        return assetRole;
    }

    public void setAssetRole(String assetRole) {
        this.assetRole = assetRole;
    }

    public String getOriginalName() {
        return originalName;
    }

    public void setOriginalName(String originalName) {
        this.originalName = originalName;
    }

    public String getOriginalRelativePath() {
        return originalRelativePath;
    }

    public void setOriginalRelativePath(String originalRelativePath) {
        this.originalRelativePath = originalRelativePath;
    }

    public String getStorageKey() {
        return storageKey;
    }

    public void setStorageKey(String storageKey) {
        this.storageKey = storageKey;
    }

    public String getMimeType() {
        return mimeType;
    }

    public void setMimeType(String mimeType) {
        this.mimeType = mimeType;
    }

    public Long getSizeBytes() {
        return sizeBytes;
    }

    public void setSizeBytes(Long sizeBytes) {
        this.sizeBytes = sizeBytes;
    }

    public String getSha256() {
        return sha256;
    }

    public void setSha256(String sha256) {
        this.sha256 = sha256;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @Override
    public String toString() {
        return "SourceAsset{id=" + id
                + ", spaceId=" + spaceId
                + ", sourceId=" + sourceId
                + ", assetRole='" + assetRole + '\''
                + ", originalName='" + originalName + '\''
                + ", mimeType='" + mimeType + '\''
                + ", sizeBytes=" + sizeBytes
                + ", sha256='" + sha256 + '\''
                + ", createdAt=" + createdAt
                + '}';
    }
}
