/**
 * Shared OpenAPI-driven API client — thin typed wrapper around
 * openapi-fetch, using types generated from the live server contract
 * (src/generated/api.d.ts).
 *
 * Generated types are produced by:
 *
 *   npm run api:generate
 *
 * which fetches OPENAPI_URL (default http://localhost:8080/v3/api-docs)
 * from a RUNNING Spring Boot server and writes src/generated/api.d.ts.
 * Never hand-write business types; always regenerate from the contract.
 */

import createClient from 'openapi-fetch';
import type { components, paths } from './generated/api.js';

/**
 * Request body types are NOT hand-written: they are extracted from
 * the generated OpenAPI contract (components.schemas), so they can
 * never drift from what the server actually declares. Generated by
 * `npm run api:generate` from /v3/api-docs.
 *
 * Note: the generated CreateLearningSpaceRequest.description is
 * `string | undefined` (optional, no null) — the wrapper below
 * therefore accepts exactly that, matching openapi-fetch's
 * requestBody typing.
 */
type CreateLearningSpaceRequest =
  components['schemas']['CreateLearningSpaceRequest'];

type CreateSourceRequest =
  components['schemas']['CreateSourceRequest'];

type CreateKnowledgeCategoryRequest =
  components['schemas']['CreateKnowledgeCategoryRequest'];

type CreateKnowledgePointRequest =
  components['schemas']['CreateKnowledgePointRequest'];

type CreateIngestionJobRequest =
  components['schemas']['CreateIngestionJobRequest'];

type LinkKnowledgePointSourcesRequest =
  components['schemas']['LinkKnowledgePointSourcesRequest'];

type UpdateAiProviderSettingsRequest =
  components['schemas']['UpdateAiProviderSettingsRequest'];

type CreateConversationRequest =
  components['schemas']['CreateConversationRequest'];

type SendMessageRequest =
  components['schemas']['SendMessageRequest'];

/**
 * Multipart wire body for {@code uploadSourceAsset} (BUSINESS-004).
 *
 * <p>Extends the real {@link FormData} so openapi-fetch detects it at
 * runtime ({@code instanceof FormData}) and passes it through WITHOUT
 * JSON serialization and WITHOUT setting Content-Type — the browser
 * then generates {@code multipart/form-data; boundary=...} itself.
 *
 * <p>The declared {@code file} property mirrors the generated
 * contract's part shape: openapi-typescript approximates OpenAPI
 * {@code format: binary} as {@code string}, so the generated
 * requestBody type is {@code { file: string }}. Declaring the same
 * shape on the FormData subclass lets the body satisfy openapi-fetch's
 * body type without {@code any} / {@code @ts-ignore} / {@code as
 * unknown as} — the actual bytes are appended at runtime via
 * {@link FormData#append}. This is the single, documented bridge for
 * the generator's binary approximation; no other endpoint uses it.
 */
class MultipartUploadBody extends FormData {
  declare file: string;
}

/**
 * Token provider abstraction. The shared client NEVER decides where
 * the access token lives (no localStorage, no cookie strategy):
 *
 * - Desktop:      future Electron safeStorage → token provider
 * - Admin Web:    future HttpOnly cookie transport → token provider
 * - tests/tools:  inline provider returning a literal token
 *
 * The provider is invoked per request; returning null/undefined means
 * the request is sent WITHOUT an Authorization header (anonymous).
 */
export interface TokenProvider {
  getAccessToken(): string | null | undefined | Promise<string | null | undefined>;
}

/**
 * Creates the shared API client bound to a base URL and a token
 * provider. All business endpoints in this package go through this
 * single client, so Desktop / Admin Web share one contract.
 *
 * @param baseUrl     e.g. http://localhost:8080
 * @param tokenProvider supplies the Authorization: Bearer value per request
 */
export function createApiClient(baseUrl: string, tokenProvider: TokenProvider) {
  // NOTE (BUSINESS-004): NO global Content-Type is set on purpose.
  // openapi-fetch sets `application/json` automatically for JSON
  // request bodies, and multipart FormData bodies must NOT carry a
  // fixed Content-Type — the browser/fetch generates
  // `multipart/form-data; boundary=...` itself. A global
  // application/json header would corrupt multipart uploads.
  const client = createClient<paths>({
    baseUrl,
  });

  return {
    /** POST /api/v1/spaces — create a LearningSpace (owner = JWT sub) */
    async createLearningSpace(body: CreateLearningSpaceRequest) {
      return client.POST('/api/v1/spaces', {
        body,
        headers: await bearerHeaders(tokenProvider),
      });
    },

    /** GET /api/v1/spaces — list MY LearningSpaces */
    async listLearningSpaces() {
      return client.GET('/api/v1/spaces', {
        headers: await bearerHeaders(tokenProvider),
      });
    },

    /** GET /api/v1/spaces/{spaceId} — get one of MY spaces */
    async getLearningSpace(spaceId: number) {
      return client.GET('/api/v1/spaces/{spaceId}', {
        params: { path: { spaceId } },
        headers: await bearerHeaders(tokenProvider),
      });
    },

    /** POST /api/v1/spaces/{spaceId}/sources — register Source metadata */
    async createSource(
      spaceId: number,
      body: CreateSourceRequest
    ) {
      return client.POST('/api/v1/spaces/{spaceId}/sources', {
        params: { path: { spaceId } },
        body,
        headers: await bearerHeaders(tokenProvider),
      });
    },

    /** GET /api/v1/spaces/{spaceId}/sources — list sources of MY space */
    async listSources(spaceId: number) {
      return client.GET('/api/v1/spaces/{spaceId}/sources', {
        params: { path: { spaceId } },
        headers: await bearerHeaders(tokenProvider),
      });
    },

    /** GET /api/v1/spaces/{spaceId}/sources/{sourceId} — one source */
    async getSource(spaceId: number, sourceId: number) {
      return client.GET('/api/v1/spaces/{spaceId}/sources/{sourceId}', {
        params: { path: { spaceId, sourceId } },
        headers: await bearerHeaders(tokenProvider),
      });
    },

    /** POST .../knowledge-categories — create a category in MY space */
    async createKnowledgeCategory(
      spaceId: number,
      body: CreateKnowledgeCategoryRequest
    ) {
      return client.POST('/api/v1/spaces/{spaceId}/knowledge-categories', {
        params: { path: { spaceId } },
        body,
        headers: await bearerHeaders(tokenProvider),
      });
    },

    /** GET .../knowledge-categories — list categories of MY space (sort_order ASC) */
    async listKnowledgeCategories(spaceId: number) {
      return client.GET('/api/v1/spaces/{spaceId}/knowledge-categories', {
        params: { path: { spaceId } },
        headers: await bearerHeaders(tokenProvider),
      });
    },

    /** GET .../knowledge-categories/{categoryId} — one category */
    async getKnowledgeCategory(spaceId: number, categoryId: number) {
      return client.GET('/api/v1/spaces/{spaceId}/knowledge-categories/{categoryId}', {
        params: { path: { spaceId, categoryId } },
        headers: await bearerHeaders(tokenProvider),
      });
    },

    /** POST .../knowledge-points — create a USER_CURATED DRAFT point */
    async createKnowledgePoint(
      spaceId: number,
      body: CreateKnowledgePointRequest
    ) {
      return client.POST('/api/v1/spaces/{spaceId}/knowledge-points', {
        params: { path: { spaceId } },
        body,
        headers: await bearerHeaders(tokenProvider),
      });
    },

    /** GET .../knowledge-points — list non-deleted points of MY space (newest first) */
    async listKnowledgePoints(spaceId: number) {
      return client.GET('/api/v1/spaces/{spaceId}/knowledge-points', {
        params: { path: { spaceId } },
        headers: await bearerHeaders(tokenProvider),
      });
    },

    /** GET .../knowledge-points/{knowledgePointId} — one point */
    async getKnowledgePoint(spaceId: number, knowledgePointId: number) {
      return client.GET('/api/v1/spaces/{spaceId}/knowledge-points/{knowledgePointId}', {
        params: { path: { spaceId, knowledgePointId } },
        headers: await bearerHeaders(tokenProvider),
      });
    },

    /** POST .../knowledge-points/{knowledgePointId}/publish — DRAFT → PUBLISHED (idempotent) */
    async publishKnowledgePoint(spaceId: number, knowledgePointId: number) {
      return client.POST(
        '/api/v1/spaces/{spaceId}/knowledge-points/{knowledgePointId}/publish',
        {
          params: { path: { spaceId, knowledgePointId } },
          headers: await bearerHeaders(tokenProvider),
        }
      );
    },

    /**
     * POST .../sources/{sourceId}/assets — upload one RAW file
     * (multipart, part name "file"). The body is a FormData subclass
     * so openapi-fetch skips JSON serialization and no Content-Type
     * is set — the browser generates the multipart boundary.
     */
    async uploadSourceAsset(spaceId: number, sourceId: number, file: File | Blob) {
      const body = new MultipartUploadBody();
      body.append('file', file);
      return client.POST('/api/v1/spaces/{spaceId}/sources/{sourceId}/assets', {
        params: { path: { spaceId, sourceId } },
        body,
        headers: await bearerHeaders(tokenProvider),
      });
    },

    /** GET .../sources/{sourceId}/assets — list assets of MY source (newest first) */
    async listSourceAssets(spaceId: number, sourceId: number) {
      return client.GET('/api/v1/spaces/{spaceId}/sources/{sourceId}/assets', {
        params: { path: { spaceId, sourceId } },
        headers: await bearerHeaders(tokenProvider),
      });
    },

    /** GET .../sources/{sourceId}/assets/{assetId} — one asset of MY source */
    async getSourceAsset(spaceId: number, sourceId: number, assetId: number) {
      return client.GET(
        '/api/v1/spaces/{spaceId}/sources/{sourceId}/assets/{assetId}',
        {
          params: { path: { spaceId, sourceId, assetId } },
          headers: await bearerHeaders(tokenProvider),
        }
      );
    },

    /**
     * POST .../sources/{sourceId}/ingestion-jobs — create an ingestion
     * job for one asset of MY source (BUSINESS-005/006: ZIP safety
     * gate / TXT-MD pipeline dispatch; 201 with the job, 422
     * INGESTION_NOT_READY for formats without a pipeline, 409 for
     * duplicate active/succeeded jobs). Response type comes from the
     * generated IngestionJobResponse schema.
     */
    async createIngestionJob(spaceId: number, sourceId: number, assetId: number) {
      const body: CreateIngestionJobRequest = { assetId };
      return client.POST(
        '/api/v1/spaces/{spaceId}/sources/{sourceId}/ingestion-jobs',
        {
          params: { path: { spaceId, sourceId } },
          body,
          headers: await bearerHeaders(tokenProvider),
        }
      );
    },

    /** GET .../sources/{sourceId}/ingestion-jobs — job history of MY source (newest first) */
    async listIngestionJobs(spaceId: number, sourceId: number) {
      return client.GET(
        '/api/v1/spaces/{spaceId}/sources/{sourceId}/ingestion-jobs',
        {
          params: { path: { spaceId, sourceId } },
          headers: await bearerHeaders(tokenProvider),
        }
      );
    },

    /** GET .../ingestion-jobs/{jobId} — one job of MY space (space-scoped) */
    async getIngestionJob(spaceId: number, jobId: number) {
      return client.GET('/api/v1/spaces/{spaceId}/ingestion-jobs/{jobId}', {
        params: { path: { spaceId, jobId } },
        headers: await bearerHeaders(tokenProvider),
      });
    },

    /** POST .../ingestion-jobs/{jobId}/retry — FAILED → PENDING (retryCount++), 409 if not FAILED */
    async retryIngestionJob(spaceId: number, jobId: number) {
      return client.POST(
        '/api/v1/spaces/{spaceId}/ingestion-jobs/{jobId}/retry',
        {
          params: { path: { spaceId, jobId } },
          headers: await bearerHeaders(tokenProvider),
        }
      );
    },

    /** GET .../sources/{sourceId}/pages — EXTRACTED pages of MY source (page_order ASC) */
    async listSourcePages(spaceId: number, sourceId: number) {
      return client.GET('/api/v1/spaces/{spaceId}/sources/{sourceId}/pages', {
        params: { path: { spaceId, sourceId } },
        headers: await bearerHeaders(tokenProvider),
      });
    },

    /**
     * GET .../sources/{sourceId}/content-blocks — EXTRACTED blocks of
     * MY source in document order; optional pageId query filter.
     * Response type comes from the generated ContentBlockResponse
     * schema.
     */
    async listContentBlocks(spaceId: number, sourceId: number, pageId?: number) {
      return client.GET(
        '/api/v1/spaces/{spaceId}/sources/{sourceId}/content-blocks',
        {
          params: {
            path: { spaceId, sourceId },
            query: pageId !== undefined ? { pageId } : undefined,
          },
          headers: await bearerHeaders(tokenProvider),
        }
      );
    },

    /**
     * POST .../knowledge-points/{knowledgePointId}/sources — link
     * ContentBlocks to MY knowledge point (BUSINESS-007). Batch
     * idempotent-add semantics live on the backend; any invalid id
     * rejects the whole batch with 404. Response is the point's full
     * current link list (generated KnowledgePointSourceResponse[]).
     */
    async addKnowledgePointSources(
      spaceId: number,
      knowledgePointId: number,
      contentBlockIds: number[]
    ) {
      const body: LinkKnowledgePointSourcesRequest = { contentBlockIds };
      return client.POST(
        '/api/v1/spaces/{spaceId}/knowledge-points/{knowledgePointId}/sources',
        {
          params: { path: { spaceId, knowledgePointId } },
          body,
          headers: await bearerHeaders(tokenProvider),
        }
      );
    },

    /** GET .../knowledge-points/{knowledgePointId}/sources — provenance links of MY point */
    async listKnowledgePointSources(spaceId: number, knowledgePointId: number) {
      return client.GET(
        '/api/v1/spaces/{spaceId}/knowledge-points/{knowledgePointId}/sources',
        {
          params: { path: { spaceId, knowledgePointId } },
          headers: await bearerHeaders(tokenProvider),
        }
      );
    },

    /** GET /api/v1/settings/ai — my AI provider settings (never returns the API key) */
    async getAiSettings() {
      return client.GET('/api/v1/settings/ai', {
        headers: await bearerHeaders(tokenProvider),
      });
    },

    /**
     * PUT /api/v1/settings/ai — update my AI provider settings.
     * Omit body.apiKey to keep the stored secret.
     */
    async putAiSettings(body: UpdateAiProviderSettingsRequest) {
      return client.PUT('/api/v1/settings/ai', {
        body,
        headers: await bearerHeaders(tokenProvider),
      });
    },

    /** POST /api/v1/settings/ai/test-connection — backend-originated provider probe */
    async testAiConnection() {
      return client.POST('/api/v1/settings/ai/test-connection', {
        headers: await bearerHeaders(tokenProvider),
      });
    },

    /** DELETE /api/v1/settings/ai/api-key — delete my stored AI API key */
    async deleteAiApiKey() {
      return client.DELETE('/api/v1/settings/ai/api-key', {
        headers: await bearerHeaders(tokenProvider),
      });
    },

    /** GET .../ai/conversations — list my ACTIVE AI conversations (paged) */
    async listConversations(
      spaceId: number,
      query?: { page?: number; size?: number }
    ) {
      return client.GET('/api/v1/spaces/{spaceId}/ai/conversations', {
        params: { path: { spaceId }, query },
        headers: await bearerHeaders(tokenProvider),
      });
    },

    /** POST .../ai/conversations — create an AI tutor conversation */
    async createConversation(
      spaceId: number,
      body?: CreateConversationRequest
    ) {
      return client.POST('/api/v1/spaces/{spaceId}/ai/conversations', {
        params: { path: { spaceId } },
        body,
        headers: await bearerHeaders(tokenProvider),
      });
    },

    /** GET .../ai/conversations/{conversationId} — one of my conversations */
    async getConversation(spaceId: number, conversationId: number) {
      return client.GET(
        '/api/v1/spaces/{spaceId}/ai/conversations/{conversationId}',
        {
          params: { path: { spaceId, conversationId } },
          headers: await bearerHeaders(tokenProvider),
        }
      );
    },

    /**
     * POST .../ai/conversations/{conversationId}/messages — send a user
     * message and receive the AI tutor reply (USER + ASSISTANT + refs).
     */
    async sendMessage(
      spaceId: number,
      conversationId: number,
      body: SendMessageRequest
    ) {
      return client.POST(
        '/api/v1/spaces/{spaceId}/ai/conversations/{conversationId}/messages',
        {
          params: { path: { spaceId, conversationId } },
          body,
          headers: await bearerHeaders(tokenProvider),
        }
      );
    },

    /** POST .../ai/conversations/{conversationId}/archive — ACTIVE → ARCHIVED */
    async archiveConversation(spaceId: number, conversationId: number) {
      return client.POST(
        '/api/v1/spaces/{spaceId}/ai/conversations/{conversationId}/archive',
        {
          params: { path: { spaceId, conversationId } },
          headers: await bearerHeaders(tokenProvider),
        }
      );
    },

    /** GET .../ai/conversations/{conversationId}/messages — list conversation messages */
    async listConversationMessages(
      spaceId: number,
      conversationId: number,
      query?: { page?: number; size?: number }
    ) {
      return (client as any).GET(
        '/api/v1/spaces/{spaceId}/ai/conversations/{conversationId}/messages',
        {
          params: { path: { spaceId, conversationId }, query },
          headers: await bearerHeaders(tokenProvider),
        }
      );
    },

    /** POST .../ai/explanations/practice-answers/{answerId} */
    async explainPracticeAnswer(spaceId: number, answerId: number) {
      return (client as any).POST(
        '/api/v1/spaces/{spaceId}/ai/explanations/practice-answers/{answerId}',
        {
          params: { path: { spaceId, answerId } },
          headers: await bearerHeaders(tokenProvider),
        }
      );
    },

    /** POST .../ai/explanations/exam-answers/{answerId} */
    async explainExamAnswer(spaceId: number, answerId: number) {
      return (client as any).POST(
        '/api/v1/spaces/{spaceId}/ai/explanations/exam-answers/{answerId}',
        {
          params: { path: { spaceId, answerId } },
          headers: await bearerHeaders(tokenProvider),
        }
      );
    },

    /** POST .../ai/study-coach — read-only study coach */
    async studyCoach(spaceId: number, body?: { question?: string }) {
      return (client as any).POST('/api/v1/spaces/{spaceId}/ai/study-coach', {
        params: { path: { spaceId } },
        body,
        headers: await bearerHeaders(tokenProvider),
      });
    },

    /** POST .../ai/generation-jobs — create a space-scoped AI generation job */
    async createAiGenerationJob(
      spaceId: number,
      body: {
        jobType: string;
        sourceId?: number;
        revisionId?: number;
        knowledgePointId?: number;
        prompt?: string;
      }
    ) {
      return (client as any).POST(
        '/api/v1/spaces/{spaceId}/ai/generation-jobs',
        {
          params: { path: { spaceId } },
          body,
          headers: await bearerHeaders(tokenProvider),
        }
      );
    },

    /** GET .../ai/generation-jobs — list my generation jobs */
    async listAiGenerationJobs(spaceId: number, query?: { page?: number; size?: number }) {
      return (client as any).GET('/api/v1/spaces/{spaceId}/ai/generation-jobs', {
        params: { path: { spaceId }, query },
        headers: await bearerHeaders(tokenProvider),
      });
    },

    /** GET .../ai/generation-jobs/{jobId} */
    async getAiGenerationJob(spaceId: number, jobId: number) {
      return (client as any).GET(
        '/api/v1/spaces/{spaceId}/ai/generation-jobs/{jobId}',
        {
          params: { path: { spaceId, jobId } },
          headers: await bearerHeaders(tokenProvider),
        }
      );
    },

    /** POST .../ai/generation-jobs/{jobId}/retry */
    async retryAiGenerationJob(spaceId: number, jobId: number) {
      return (client as any).POST(
        '/api/v1/spaces/{spaceId}/ai/generation-jobs/{jobId}/retry',
        {
          params: { path: { spaceId, jobId } },
          headers: await bearerHeaders(tokenProvider),
        }
      );
    },

    /** GET .../sources/{sourceId}/assets/{assetId}/content — authorized RAW download */
    async downloadSourceAssetRaw(spaceId: number, sourceId: number, assetId: number) {
      return (client as any).GET(
        '/api/v1/spaces/{spaceId}/sources/{sourceId}/assets/{assetId}/content',
        {
          params: { path: { spaceId, sourceId, assetId } },
          headers: await bearerHeaders(tokenProvider),
        }
      );
    },

    /** DELETE .../sources/{sourceId}/folder-sync/snapshot/{snapshotId} */
    async deleteFolderSyncSnapshot(spaceId: number, sourceId: number, snapshotId: number) {
      return (client as any).DELETE(
        '/api/v1/spaces/{spaceId}/sources/{sourceId}/folder-sync/snapshot/{snapshotId}',
        {
          params: { path: { spaceId, sourceId, snapshotId } },
          headers: await bearerHeaders(tokenProvider),
        }
      );
    },

    /** GET /api/v1/admin/system-config/registry — ADMIN typed config registry */
    async adminSystemConfigRegistry() {
      return (client as any).GET('/api/v1/admin/system-config/registry', {
        headers: await bearerHeaders(tokenProvider),
      });
    },

    /** PUT /api/v1/admin/system-config/{key} — ADMIN set runtime config value only */
    async adminUpsertSystemConfig(key: string, value: string) {
      return (client as any).PUT('/api/v1/admin/system-config/{key}', {
        params: { path: { key } },
        body: { value },
        headers: await bearerHeaders(tokenProvider),
      });
    },

    /** GET /api/v1/admin/sources — ADMIN source governance list */
    async adminListSources(query?: { q?: string; spaceId?: number; page?: number; size?: number }) {
      return (client as any).GET('/api/v1/admin/sources', {
        query,
        headers: await bearerHeaders(tokenProvider),
      });
    },

    /** POST /api/v1/admin/sources/jobs/{jobId}/retry */
    async adminRetryIngestionJob(jobId: number) {
      return (client as any).POST('/api/v1/admin/sources/jobs/{jobId}/retry', {
        params: { path: { jobId } },
        headers: await bearerHeaders(tokenProvider),
      });
    },

    /** POST .../notes/{noteId}/knowledge-points — link knowledge points to MY note */
    async addNoteKnowledgePoints(spaceId: number, noteId: number, kpIds: number[]) {
      return (client as any).POST(
        '/api/v1/spaces/{spaceId}/notes/{noteId}/knowledge-points',
        {
          params: { path: { spaceId, noteId } },
          body: kpIds,
          headers: await bearerHeaders(tokenProvider),
        }
      );
    },

    /** GET .../notes/{noteId}/knowledge-points — list knowledge points of MY note */
    async listNoteKnowledgePoints(spaceId: number, noteId: number) {
      return (client as any).GET(
        '/api/v1/spaces/{spaceId}/notes/{noteId}/knowledge-points',
        {
          params: { path: { spaceId, noteId } },
          headers: await bearerHeaders(tokenProvider),
        }
      );
    },

    /** DELETE .../notes/{noteId}/knowledge-points/{kpId} — unlink a knowledge point from MY note */
    async removeNoteKnowledgePoint(spaceId: number, noteId: number, kpId: number) {
      return (client as any).DELETE(
        '/api/v1/spaces/{spaceId}/notes/{noteId}/knowledge-points/{kpId}',
        {
          params: { path: { spaceId, noteId, kpId } },
          headers: await bearerHeaders(tokenProvider),
        }
      );
    },

    /** POST .../notes/{noteId}/source-blocks — link content blocks to MY note */
    async addNoteSourceBlocks(spaceId: number, noteId: number, blockIds: number[]) {
      return (client as any).POST(
        '/api/v1/spaces/{spaceId}/notes/{noteId}/source-blocks',
        {
          params: { path: { spaceId, noteId } },
          body: blockIds,
          headers: await bearerHeaders(tokenProvider),
        }
      );
    },

    /** GET .../notes/{noteId}/source-blocks — list content blocks of MY note */
    async listNoteSourceBlocks(spaceId: number, noteId: number) {
      return (client as any).GET(
        '/api/v1/spaces/{spaceId}/notes/{noteId}/source-blocks',
        {
          params: { path: { spaceId, noteId } },
          headers: await bearerHeaders(tokenProvider),
        }
      );
    },

    /** DELETE .../notes/{noteId}/source-blocks/{blockId} — unlink a content block from MY note */
    async removeNoteSourceBlock(spaceId: number, noteId: number, blockId: number) {
      return (client as any).DELETE(
        '/api/v1/spaces/{spaceId}/notes/{noteId}/source-blocks/{blockId}',
        {
          params: { path: { spaceId, noteId, blockId } },
          headers: await bearerHeaders(tokenProvider),
        }
      );
    },

    /** POST .../questions/{questionId}/source-blocks — link content blocks to MY question */
    async addQuestionSourceBlocks(spaceId: number, questionId: number, blockIds: number[]) {
      return (client as any).POST(
        '/api/v1/spaces/{spaceId}/questions/{questionId}/source-blocks',
        {
          params: { path: { spaceId, questionId } },
          body: blockIds,
          headers: await bearerHeaders(tokenProvider),
        }
      );
    },

    /** GET .../questions/{questionId}/source-blocks — list content blocks of MY question */
    async listQuestionSourceBlocks(spaceId: number, questionId: number) {
      return (client as any).GET(
        '/api/v1/spaces/{spaceId}/questions/{questionId}/source-blocks',
        {
          params: { path: { spaceId, questionId } },
          headers: await bearerHeaders(tokenProvider),
        }
      );
    },

    /** DELETE .../questions/{questionId}/source-blocks/{blockId} — unlink a content block from MY question */
    async removeQuestionSourceBlock(spaceId: number, questionId: number, blockId: number) {
      return (client as any).DELETE(
        '/api/v1/spaces/{spaceId}/questions/{questionId}/source-blocks/{blockId}',
        {
          params: { path: { spaceId, questionId, blockId } },
          headers: await bearerHeaders(tokenProvider),
        }
      );
    },

    /** POST .../knowledge-points/{kpId}/relations — add a relation from MY knowledge point */
    async addKnowledgePointRelation(
      spaceId: number,
      kpId: number,
      body: { relationType: string; targetKpId: number; weight?: number; notes?: string }
    ) {
      return (client as any).POST(
        '/api/v1/spaces/{spaceId}/knowledge-points/{kpId}/relations',
        {
          params: { path: { spaceId, kpId } },
          body,
          headers: await bearerHeaders(tokenProvider),
        }
      );
    },

    /** GET .../knowledge-points/{kpId}/relations — list relations of MY knowledge point */
    async listKnowledgePointRelations(spaceId: number, kpId: number) {
      return (client as any).GET(
        '/api/v1/spaces/{spaceId}/knowledge-points/{kpId}/relations',
        {
          params: { path: { spaceId, kpId } },
          headers: await bearerHeaders(tokenProvider),
        }
      );
    },

    /** DELETE .../knowledge-points/{kpId}/relations/{relationId} — remove a relation */
    async removeKnowledgePointRelation(spaceId: number, kpId: number, relationId: number) {
      return (client as any).DELETE(
        '/api/v1/spaces/{spaceId}/knowledge-points/{kpId}/relations/{relationId}',
        {
          params: { path: { spaceId, kpId, relationId } },
          headers: await bearerHeaders(tokenProvider),
        }
      );
    },

    /** POST .../sources/{sourceId}/folder-sync/snapshot — create a folder import snapshot */
    async createFolderSyncSnapshot(spaceId: number, sourceId: number) {
      return (client as any).POST(
        '/api/v1/spaces/{spaceId}/sources/{sourceId}/folder-sync/snapshot',
        {
          params: { path: { spaceId, sourceId } },
          headers: await bearerHeaders(tokenProvider),
        }
      );
    },

    /** POST .../sources/{sourceId}/folder-sync/snapshot/{snapshotId}/entries — submit folder entries */
    async submitFolderSyncEntries(
      spaceId: number,
      sourceId: number,
      snapshotId: number,
      entries: { relativePath: string; sha256?: string }[]
    ) {
      return (client as any).POST(
        '/api/v1/spaces/{spaceId}/sources/{sourceId}/folder-sync/snapshot/{snapshotId}/entries',
        {
          params: { path: { spaceId, sourceId, snapshotId } },
          body: entries,
          headers: await bearerHeaders(tokenProvider),
        }
      );
    },

    /** GET .../sources/{sourceId}/folder-sync/snapshot — list folder sync snapshots */
    async listFolderSyncSnapshots(spaceId: number, sourceId: number) {
      return (client as any).GET(
        '/api/v1/spaces/{spaceId}/sources/{sourceId}/folder-sync/snapshot',
        {
          params: { path: { spaceId, sourceId } },
          headers: await bearerHeaders(tokenProvider),
        }
      );
    },

    /** GET .../sources/{sourceId}/folder-sync/snapshot/{snapshotId} — get one snapshot */
    async getFolderSyncSnapshot(spaceId: number, sourceId: number, snapshotId: number) {
      return (client as any).GET(
        '/api/v1/spaces/{spaceId}/sources/{sourceId}/folder-sync/snapshot/{snapshotId}',
        {
          params: { path: { spaceId, sourceId, snapshotId } },
          headers: await bearerHeaders(tokenProvider),
        }
      );
    },

    /** GET .../sources/{sourceId}/folder-sync/snapshot/{snapshotId}/entries — list entries of a snapshot */
    async listFolderSyncEntries(spaceId: number, sourceId: number, snapshotId: number) {
      return (client as any).GET(
        '/api/v1/spaces/{spaceId}/sources/{sourceId}/folder-sync/snapshot/{snapshotId}/entries',
        {
          params: { path: { spaceId, sourceId, snapshotId } },
          headers: await bearerHeaders(tokenProvider),
        }
      );
    },

    /** POST .../sources/{sourceId}/versions/compare — compare two extraction revisions */
    async compareSourceVersions(
      spaceId: number,
      sourceId: number,
      body: { fromRevisionId: number; toRevisionId: number }
    ) {
      return (client as any).POST(
        '/api/v1/spaces/{spaceId}/sources/{sourceId}/versions/compare',
        {
          params: { path: { spaceId, sourceId } },
          body,
          headers: await bearerHeaders(tokenProvider),
        }
      );
    },
  };
}

async function bearerHeaders(tokenProvider: TokenProvider) {
  const token = await tokenProvider.getAccessToken();
  return token ? { Authorization: `Bearer ${token}` } : {};
}

export type ApiClient = ReturnType<typeof createApiClient>;
