/**
 * Shared OpenAPI-driven API client — thin typed wrapper around
 * openapi-fetch, using types generated from the live server contract
 * (src/generated/api.d.ts).
 *
 * Generated types are produced by:
 *
 *   npm run api:generate
 *
 * which fetches OPENAPI_URL (default http://localhost:8080/v3/api-docs)
 * from a RUNNING Spring Boot server and writes src/generated/api.d.ts.
 * Never hand-write business types; always regenerate from the contract.
 */

import createClient from 'openapi-fetch';
import type { components, paths } from './generated/api.js';

/**
 * Request body types are NOT hand-written: they are extracted from
 * the generated OpenAPI contract (components.schemas), so they can
 * never drift from what the server actually declares. Generated by
 * `npm run api:generate` from /v3/api-docs.
 *
 * Note: the generated CreateLearningSpaceRequest.description is
 * `string | undefined` (optional, no null) — the wrapper below
 * therefore accepts exactly that, matching openapi-fetch's
 * requestBody typing.
 */
type CreateLearningSpaceRequest =
  components['schemas']['CreateLearningSpaceRequest'];

type CreateSourceRequest =
  components['schemas']['CreateSourceRequest'];

type CreateKnowledgeCategoryRequest =
  components['schemas']['CreateKnowledgeCategoryRequest'];

type CreateKnowledgePointRequest =
  components['schemas']['CreateKnowledgePointRequest'];

type CreateIngestionJobRequest =
  components['schemas']['CreateIngestionJobRequest'];

type LinkKnowledgePointSourcesRequest =
  components['schemas']['LinkKnowledgePointSourcesRequest'];

/**
 * Multipart wire body for {@code uploadSourceAsset} (BUSINESS-004).
 *
 * <p>Extends the real {@link FormData} so openapi-fetch detects it at
 * runtime ({@code instanceof FormData}) and passes it through WITHOUT
 * JSON serialization and WITHOUT setting Content-Type — the browser
 * then generates {@code multipart/form-data; boundary=...} itself.
 *
 * <p>The declared {@code file} property mirrors the generated
 * contract's part shape: openapi-typescript approximates OpenAPI
 * {@code format: binary} as {@code string}, so the generated
 * requestBody type is {@code { file: string }}. Declaring the same
 * shape on the FormData subclass lets the body satisfy openapi-fetch's
 * body type without {@code any} / {@code @ts-ignore} / {@code as
 * unknown as} — the actual bytes are appended at runtime via
 * {@link FormData#append}. This is the single, documented bridge for
 * the generator's binary approximation; no other endpoint uses it.
 */
class MultipartUploadBody extends FormData {
  declare file: string;
}

/**
 * Token provider abstraction. The shared client NEVER decides where
 * the access token lives (no localStorage, no cookie strategy):
 *
 * - Desktop:      future Electron safeStorage → token provider
 * - Admin Web:    future HttpOnly cookie transport → token provider
 * - tests/tools:  inline provider returning a literal token
 *
 * The provider is invoked per request; returning null/undefined means
 * the request is sent WITHOUT an Authorization header (anonymous).
 */
export interface TokenProvider {
  getAccessToken(): string | null | undefined | Promise<string | null | undefined>;
}

/**
 * Creates the shared API client bound to a base URL and a token
 * provider. All business endpoints in this package go through this
 * single client, so Desktop / Admin Web share one contract.
 *
 * @param baseUrl     e.g. http://localhost:8080
 * @param tokenProvider supplies the Authorization: Bearer value per request
 */
export function createApiClient(baseUrl: string, tokenProvider: TokenProvider) {
  // NOTE (BUSINESS-004): NO global Content-Type is set on purpose.
  // openapi-fetch sets `application/json` automatically for JSON
  // request bodies, and multipart FormData bodies must NOT carry a
  // fixed Content-Type — the browser/fetch generates
  // `multipart/form-data; boundary=...` itself. A global
  // application/json header would corrupt multipart uploads.
  const client = createClient<paths>({
    baseUrl,
  });

  return {
    /** POST /api/v1/spaces — create a LearningSpace (owner = JWT sub) */
    async createLearningSpace(body: CreateLearningSpaceRequest) {
      return client.POST('/api/v1/spaces', {
        body,
        headers: await bearerHeaders(tokenProvider),
      });
    },

    /** GET /api/v1/spaces — list MY LearningSpaces */
    async listLearningSpaces() {
      return client.GET('/api/v1/spaces', {
        headers: await bearerHeaders(tokenProvider),
      });
    },

    /** GET /api/v1/spaces/{spaceId} — get one of MY spaces */
    async getLearningSpace(spaceId: number) {
      return client.GET('/api/v1/spaces/{spaceId}', {
        params: { path: { spaceId } },
        headers: await bearerHeaders(tokenProvider),
      });
    },

    /** POST /api/v1/spaces/{spaceId}/sources — register Source metadata */
    async createSource(
      spaceId: number,
      body: CreateSourceRequest
    ) {
      return client.POST('/api/v1/spaces/{spaceId}/sources', {
        params: { path: { spaceId } },
        body,
        headers: await bearerHeaders(tokenProvider),
      });
    },

    /** GET /api/v1/spaces/{spaceId}/sources — list sources of MY space */
    async listSources(spaceId: number) {
      return client.GET('/api/v1/spaces/{spaceId}/sources', {
        params: { path: { spaceId } },
        headers: await bearerHeaders(tokenProvider),
      });
    },

    /** GET /api/v1/spaces/{spaceId}/sources/{sourceId} — one source */
    async getSource(spaceId: number, sourceId: number) {
      return client.GET('/api/v1/spaces/{spaceId}/sources/{sourceId}', {
        params: { path: { spaceId, sourceId } },
        headers: await bearerHeaders(tokenProvider),
      });
    },

    /** POST .../knowledge-categories — create a category in MY space */
    async createKnowledgeCategory(
      spaceId: number,
      body: CreateKnowledgeCategoryRequest
    ) {
      return client.POST('/api/v1/spaces/{spaceId}/knowledge-categories', {
        params: { path: { spaceId } },
        body,
        headers: await bearerHeaders(tokenProvider),
      });
    },

    /** GET .../knowledge-categories — list categories of MY space (sort_order ASC) */
    async listKnowledgeCategories(spaceId: number) {
      return client.GET('/api/v1/spaces/{spaceId}/knowledge-categories', {
        params: { path: { spaceId } },
        headers: await bearerHeaders(tokenProvider),
      });
    },

    /** GET .../knowledge-categories/{categoryId} — one category */
    async getKnowledgeCategory(spaceId: number, categoryId: number) {
      return client.GET('/api/v1/spaces/{spaceId}/knowledge-categories/{categoryId}', {
        params: { path: { spaceId, categoryId } },
        headers: await bearerHeaders(tokenProvider),
      });
    },

    /** POST .../knowledge-points — create a USER_CURATED DRAFT point */
    async createKnowledgePoint(
      spaceId: number,
      body: CreateKnowledgePointRequest
    ) {
      return client.POST('/api/v1/spaces/{spaceId}/knowledge-points', {
        params: { path: { spaceId } },
        body,
        headers: await bearerHeaders(tokenProvider),
      });
    },

    /** GET .../knowledge-points — list non-deleted points of MY space (newest first) */
    async listKnowledgePoints(spaceId: number) {
      return client.GET('/api/v1/spaces/{spaceId}/knowledge-points', {
        params: { path: { spaceId } },
        headers: await bearerHeaders(tokenProvider),
      });
    },

    /** GET .../knowledge-points/{knowledgePointId} — one point */
    async getKnowledgePoint(spaceId: number, knowledgePointId: number) {
      return client.GET('/api/v1/spaces/{spaceId}/knowledge-points/{knowledgePointId}', {
        params: { path: { spaceId, knowledgePointId } },
        headers: await bearerHeaders(tokenProvider),
      });
    },

    /** POST .../knowledge-points/{knowledgePointId}/publish — DRAFT → PUBLISHED (idempotent) */
    async publishKnowledgePoint(spaceId: number, knowledgePointId: number) {
      return client.POST(
        '/api/v1/spaces/{spaceId}/knowledge-points/{knowledgePointId}/publish',
        {
          params: { path: { spaceId, knowledgePointId } },
          headers: await bearerHeaders(tokenProvider),
        }
      );
    },

    /**
     * POST .../sources/{sourceId}/assets — upload one RAW file
     * (multipart, part name "file"). The body is a FormData subclass
     * so openapi-fetch skips JSON serialization and no Content-Type
     * is set — the browser generates the multipart boundary.
     */
    async uploadSourceAsset(spaceId: number, sourceId: number, file: File | Blob) {
      const body = new MultipartUploadBody();
      body.append('file', file);
      return client.POST('/api/v1/spaces/{spaceId}/sources/{sourceId}/assets', {
        params: { path: { spaceId, sourceId } },
        body,
        headers: await bearerHeaders(tokenProvider),
      });
    },

    /** GET .../sources/{sourceId}/assets — list assets of MY source (newest first) */
    async listSourceAssets(spaceId: number, sourceId: number) {
      return client.GET('/api/v1/spaces/{spaceId}/sources/{sourceId}/assets', {
        params: { path: { spaceId, sourceId } },
        headers: await bearerHeaders(tokenProvider),
      });
    },

    /** GET .../sources/{sourceId}/assets/{assetId} — one asset of MY source */
    async getSourceAsset(spaceId: number, sourceId: number, assetId: number) {
      return client.GET(
        '/api/v1/spaces/{spaceId}/sources/{sourceId}/assets/{assetId}',
        {
          params: { path: { spaceId, sourceId, assetId } },
          headers: await bearerHeaders(tokenProvider),
        }
      );
    },

    /**
     * POST .../sources/{sourceId}/ingestion-jobs — create an ingestion
     * job for one asset of MY source (BUSINESS-005/006: ZIP safety
     * gate / TXT-MD pipeline dispatch; 201 with the job, 422
     * INGESTION_NOT_READY for formats without a pipeline, 409 for
     * duplicate active/succeeded jobs). Response type comes from the
     * generated IngestionJobResponse schema.
     */
    async createIngestionJob(spaceId: number, sourceId: number, assetId: number) {
      const body: CreateIngestionJobRequest = { assetId };
      return client.POST(
        '/api/v1/spaces/{spaceId}/sources/{sourceId}/ingestion-jobs',
        {
          params: { path: { spaceId, sourceId } },
          body,
          headers: await bearerHeaders(tokenProvider),
        }
      );
    },

    /** GET .../sources/{sourceId}/ingestion-jobs — job history of MY source (newest first) */
    async listIngestionJobs(spaceId: number, sourceId: number) {
      return client.GET(
        '/api/v1/spaces/{spaceId}/sources/{sourceId}/ingestion-jobs',
        {
          params: { path: { spaceId, sourceId } },
          headers: await bearerHeaders(tokenProvider),
        }
      );
    },

    /** GET .../ingestion-jobs/{jobId} — one job of MY space (space-scoped) */
    async getIngestionJob(spaceId: number, jobId: number) {
      return client.GET('/api/v1/spaces/{spaceId}/ingestion-jobs/{jobId}', {
        params: { path: { spaceId, jobId } },
        headers: await bearerHeaders(tokenProvider),
      });
    },

    /** POST .../ingestion-jobs/{jobId}/retry — FAILED → PENDING (retryCount++), 409 if not FAILED */
    async retryIngestionJob(spaceId: number, jobId: number) {
      return client.POST(
        '/api/v1/spaces/{spaceId}/ingestion-jobs/{jobId}/retry',
        {
          params: { path: { spaceId, jobId } },
          headers: await bearerHeaders(tokenProvider),
        }
      );
    },

    /** GET .../sources/{sourceId}/pages — EXTRACTED pages of MY source (page_order ASC) */
    async listSourcePages(spaceId: number, sourceId: number) {
      return client.GET('/api/v1/spaces/{spaceId}/sources/{sourceId}/pages', {
        params: { path: { spaceId, sourceId } },
        headers: await bearerHeaders(tokenProvider),
      });
    },

    /**
     * GET .../sources/{sourceId}/content-blocks — EXTRACTED blocks of
     * MY source in document order; optional pageId query filter.
     * Response type comes from the generated ContentBlockResponse
     * schema.
     */
    async listContentBlocks(spaceId: number, sourceId: number, pageId?: number) {
      return client.GET(
        '/api/v1/spaces/{spaceId}/sources/{sourceId}/content-blocks',
        {
          params: {
            path: { spaceId, sourceId },
            query: pageId !== undefined ? { pageId } : undefined,
          },
          headers: await bearerHeaders(tokenProvider),
        }
      );
    },

    /**
     * POST .../knowledge-points/{knowledgePointId}/sources — link
     * ContentBlocks to MY knowledge point (BUSINESS-007). Batch
     * idempotent-add semantics live on the backend; any invalid id
     * rejects the whole batch with 404. Response is the point's full
     * current link list (generated KnowledgePointSourceResponse[]).
     */
    async addKnowledgePointSources(
      spaceId: number,
      knowledgePointId: number,
      contentBlockIds: number[]
    ) {
      const body: LinkKnowledgePointSourcesRequest = { contentBlockIds };
      return client.POST(
        '/api/v1/spaces/{spaceId}/knowledge-points/{knowledgePointId}/sources',
        {
          params: { path: { spaceId, knowledgePointId } },
          body,
          headers: await bearerHeaders(tokenProvider),
        }
      );
    },

    /** GET .../knowledge-points/{knowledgePointId}/sources — provenance links of MY point */
    async listKnowledgePointSources(spaceId: number, knowledgePointId: number) {
      return client.GET(
        '/api/v1/spaces/{spaceId}/knowledge-points/{knowledgePointId}/sources',
        {
          params: { path: { spaceId, knowledgePointId } },
          headers: await bearerHeaders(tokenProvider),
        }
      );
    },
  };
}

async function bearerHeaders(tokenProvider: TokenProvider) {
  const token = await tokenProvider.getAccessToken();
  return token ? { Authorization: `Bearer ${token}` } : {};
}

export type ApiClient = ReturnType<typeof createApiClient>;
