/**
 * Shared OpenAPI-driven API client — thin typed wrapper around
 * openapi-fetch, using types generated from the live server contract
 * (src/generated/api.d.ts).
 *
 * Generated types are produced by:
 *
 *   npm run api:generate
 *
 * which fetches OPENAPI_URL (default http://localhost:8080/v3/api-docs)
 * from a RUNNING Spring Boot server and writes src/generated/api.d.ts.
 * Never hand-write business types; always regenerate from the contract.
 */

import createClient from 'openapi-fetch';
import type { components, paths } from './generated/api.js';

/**
 * Request body types are NOT hand-written: they are extracted from
 * the generated OpenAPI contract (components.schemas), so they can
 * never drift from what the server actually declares. Generated by
 * `npm run api:generate` from /v3/api-docs.
 *
 * Note: the generated CreateLearningSpaceRequest.description is
 * `string | undefined` (optional, no null) — the wrapper below
 * therefore accepts exactly that, matching openapi-fetch's
 * requestBody typing.
 */
type CreateLearningSpaceRequest =
  components['schemas']['CreateLearningSpaceRequest'];

type CreateSourceRequest =
  components['schemas']['CreateSourceRequest'];

type CreateKnowledgeCategoryRequest =
  components['schemas']['CreateKnowledgeCategoryRequest'];

type CreateKnowledgePointRequest =
  components['schemas']['CreateKnowledgePointRequest'];

/**
 * Token provider abstraction. The shared client NEVER decides where
 * the access token lives (no localStorage, no cookie strategy):
 *
 * - Desktop:      future Electron safeStorage → token provider
 * - Admin Web:    future HttpOnly cookie transport → token provider
 * - tests/tools:  inline provider returning a literal token
 *
 * The provider is invoked per request; returning null/undefined means
 * the request is sent WITHOUT an Authorization header (anonymous).
 */
export interface TokenProvider {
  getAccessToken(): string | null | undefined | Promise<string | null | undefined>;
}

/**
 * Creates the shared API client bound to a base URL and a token
 * provider. All business endpoints in this package go through this
 * single client, so Desktop / Admin Web share one contract.
 *
 * @param baseUrl     e.g. http://localhost:8080
 * @param tokenProvider supplies the Authorization: Bearer value per request
 */
export function createApiClient(baseUrl: string, tokenProvider: TokenProvider) {
  const client = createClient<paths>({
    baseUrl,
    headers: {
      'Content-Type': 'application/json',
    },
  });

  return {
    /** POST /api/v1/spaces — create a LearningSpace (owner = JWT sub) */
    async createLearningSpace(body: CreateLearningSpaceRequest) {
      return client.POST('/api/v1/spaces', {
        body,
        headers: await bearerHeaders(tokenProvider),
      });
    },

    /** GET /api/v1/spaces — list MY LearningSpaces */
    async listLearningSpaces() {
      return client.GET('/api/v1/spaces', {
        headers: await bearerHeaders(tokenProvider),
      });
    },

    /** GET /api/v1/spaces/{spaceId} — get one of MY spaces */
    async getLearningSpace(spaceId: number) {
      return client.GET('/api/v1/spaces/{spaceId}', {
        params: { path: { spaceId } },
        headers: await bearerHeaders(tokenProvider),
      });
    },

    /** POST /api/v1/spaces/{spaceId}/sources — register Source metadata */
    async createSource(
      spaceId: number,
      body: CreateSourceRequest
    ) {
      return client.POST('/api/v1/spaces/{spaceId}/sources', {
        params: { path: { spaceId } },
        body,
        headers: await bearerHeaders(tokenProvider),
      });
    },

    /** GET /api/v1/spaces/{spaceId}/sources — list sources of MY space */
    async listSources(spaceId: number) {
      return client.GET('/api/v1/spaces/{spaceId}/sources', {
        params: { path: { spaceId } },
        headers: await bearerHeaders(tokenProvider),
      });
    },

    /** GET /api/v1/spaces/{spaceId}/sources/{sourceId} — one source */
    async getSource(spaceId: number, sourceId: number) {
      return client.GET('/api/v1/spaces/{spaceId}/sources/{sourceId}', {
        params: { path: { spaceId, sourceId } },
        headers: await bearerHeaders(tokenProvider),
      });
    },

    /** POST .../knowledge-categories — create a category in MY space */
    async createKnowledgeCategory(
      spaceId: number,
      body: CreateKnowledgeCategoryRequest
    ) {
      return client.POST('/api/v1/spaces/{spaceId}/knowledge-categories', {
        params: { path: { spaceId } },
        body,
        headers: await bearerHeaders(tokenProvider),
      });
    },

    /** GET .../knowledge-categories — list categories of MY space (sort_order ASC) */
    async listKnowledgeCategories(spaceId: number) {
      return client.GET('/api/v1/spaces/{spaceId}/knowledge-categories', {
        params: { path: { spaceId } },
        headers: await bearerHeaders(tokenProvider),
      });
    },

    /** GET .../knowledge-categories/{categoryId} — one category */
    async getKnowledgeCategory(spaceId: number, categoryId: number) {
      return client.GET('/api/v1/spaces/{spaceId}/knowledge-categories/{categoryId}', {
        params: { path: { spaceId, categoryId } },
        headers: await bearerHeaders(tokenProvider),
      });
    },

    /** POST .../knowledge-points — create a USER_CURATED DRAFT point */
    async createKnowledgePoint(
      spaceId: number,
      body: CreateKnowledgePointRequest
    ) {
      return client.POST('/api/v1/spaces/{spaceId}/knowledge-points', {
        params: { path: { spaceId } },
        body,
        headers: await bearerHeaders(tokenProvider),
      });
    },

    /** GET .../knowledge-points — list non-deleted points of MY space (newest first) */
    async listKnowledgePoints(spaceId: number) {
      return client.GET('/api/v1/spaces/{spaceId}/knowledge-points', {
        params: { path: { spaceId } },
        headers: await bearerHeaders(tokenProvider),
      });
    },

    /** GET .../knowledge-points/{knowledgePointId} — one point */
    async getKnowledgePoint(spaceId: number, knowledgePointId: number) {
      return client.GET('/api/v1/spaces/{spaceId}/knowledge-points/{knowledgePointId}', {
        params: { path: { spaceId, knowledgePointId } },
        headers: await bearerHeaders(tokenProvider),
      });
    },

    /** POST .../knowledge-points/{knowledgePointId}/publish — DRAFT → PUBLISHED (idempotent) */
    async publishKnowledgePoint(spaceId: number, knowledgePointId: number) {
      return client.POST(
        '/api/v1/spaces/{spaceId}/knowledge-points/{knowledgePointId}/publish',
        {
          params: { path: { spaceId, knowledgePointId } },
          headers: await bearerHeaders(tokenProvider),
        }
      );
    },
  };
}

async function bearerHeaders(tokenProvider: TokenProvider) {
  const token = await tokenProvider.getAccessToken();
  return token ? { Authorization: `Bearer ${token}` } : {};
}

export type ApiClient = ReturnType<typeof createApiClient>;
